GET http://localhost:3000/

###

POST http://localhost:3000/campaigns

{
    "name": "Change",
    "content": "Change Password",
    "emails": ["test@test.com"]
}

###

GET http://localhost:3000/campaigns/cvkufgftlrri36017rc0