GET http://localhost:3000/

###

POST http://localhost:3000/campaigns

{
    "name": "Change",
    "content": "Change Password",
    "emails": ["test@test.com"]
}

###

GET http://localhost:3000/campaigns/cvmvq8ntlrrlil5meljg

###

PATCH http://localhost:3000/campaigns/cancel/cvkufgftlrri36017rc0

###

DELETE http://localhost:3000/campaigns/delete/cvmvfv7tlrrlv73uuhag